<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="AtemSharp" />
    <PackageReference Include="AtemSharp.MSDependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="System.Reactive" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cgf.CameraControl.Core\Cgf.CameraControl.Core.csproj" />
  </ItemGroup>

</Project>
