<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="SDL3-CS" />
    <PackageReference Include="SDL3-CS.Linux" />
    <PackageReference Include="SDL3-CS.MacOS" />
    <PackageReference Include="SDL3-CS.Windows" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cgf.CameraControl.Core\Cgf.CameraControl.Core.csproj" />
  </ItemGroup>

</Project>
