<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Cgf.CameraControl.Cameras.ViscaOverIp\Cgf.CameraControl.Cameras.ViscaOverIp.csproj" />
  </ItemGroup>

</Project>
