using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Cgf.CameraControl.Licenses.Generator;

/// Turns the nuget-license report into the list the licences window shows.
///
/// The report is fixed at build time, so reading it, parsing it and formatting it again on every
/// start would be work done to arrive at a constant. What this emits is the finished strings the
/// window binds to, which also keeps the published binary honest: nothing about the notices depends
/// on a resource being found or a deserializer surviving trimming.
[Generator]
public sealed class ThirdPartyLicenseGenerator : IIncrementalGenerator
{
    private const string FileName = "third-party-licenses.json";

    private static readonly DiagnosticDescriptor Missing = new(
        "CGFLIC001",
        "The third party licence report is missing",
        "No additional file named " + FileName + " was supplied, so the licences window would be empty",
        "Licences",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor Unreadable = new(
        "CGFLIC002",
        "The third party licence report cannot be read",
        "{0} is not the JSON array nuget-license writes: {1}",
        "Licences",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // A tuple rather than a class of its own: what travels the pipeline has to compare by value
        // or the generator runs again on every keystroke, and netstandard2.0 has no records without
        // a polyfill package to supply the init accessor they compile to.
        var reports = context.AdditionalTextsProvider
            .Where(text => Path.GetFileName(text.Path) == FileName)
            .Select((text, token) => (Path: text.Path, Content: text.GetText(token)?.ToString() ?? string.Empty))
            .Collect();

        context.RegisterSourceOutput(reports, Emit);
    }

    private static void Emit(SourceProductionContext context, ImmutableArray<(string Path, string Content)> reports)
    {
        if (reports.Length == 0)
        {
            context.ReportDiagnostic(Diagnostic.Create(Missing, Location.None));
            return;
        }

        var packages = new List<Package>();
        foreach (var report in reports)
        {
            try
            {
                packages.AddRange(Parse(report.Content));
            }
            catch (JsonException ex)
            {
                context.ReportDiagnostic(Diagnostic.Create(Unreadable, Location.None, report.Path, ex.Message));
                return;
            }
            catch (InvalidReportException ex)
            {
                context.ReportDiagnostic(Diagnostic.Create(Unreadable, Location.None, report.Path, ex.Message));
                return;
            }
        }

        context.AddSource("ThirdPartyLicenses.g.cs", SourceText.From(Render(packages), Encoding.UTF8));
    }

    /// Ordered here rather than trusted from the file, so the window reads the same however the
    /// report was produced.
    private static IEnumerable<Package> Parse(string content)
    {
        if (JToken.Parse(content) is not JArray entries)
        {
            throw new InvalidReportException("the root is not an array");
        }

        return entries
            .OfType<JObject>()
            .Select(entry => new Package(
                $"{Text(entry, "PackageId")} {Text(entry, "PackageVersion")}".Trim(),
                Text(entry, "License"),
                Text(entry, "Authors"),
                Text(entry, "PackageProjectUrl")))
            .OrderBy(package => package.Title, System.StringComparer.OrdinalIgnoreCase)
            .ToList();
    }

    private static string? Text(JObject entry, string name) =>
        entry[name] is JValue { Type: JTokenType.String } value ? (string?)value.Value : null;

    private static string Render(IReadOnlyList<Package> packages)
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated/>");
        source.AppendLine("#nullable enable");
        source.AppendLine();
        source.AppendLine("namespace Cgf.CameraControl.App.Licenses;");
        source.AppendLine();
        source.AppendLine("/// The packages this application ships, as nuget-license reported them at build time.");
        source.AppendLine("public static class ThirdPartyLicenses");
        source.AppendLine("{");
        source.AppendLine("    public static global::System.Collections.Generic.IReadOnlyList<ThirdPartyLicense> All { get; } =");
        source.AppendLine("    [");

        foreach (var package in packages)
        {
            source.Append("        new(");
            source.Append(Literal(package.Title));
            source.Append(", ");
            source.Append(Literal(package.License));
            source.Append(", ");
            source.Append(Literal(package.Authors));
            source.Append(", ");
            source.Append(Literal(package.ProjectUrl));
            source.AppendLine("),");
        }

        source.AppendLine("    ];");
        source.AppendLine("}");
        return source.ToString();
    }

    private static string Literal(string? value) =>
        value is null ? "null" : SyntaxFactory.Literal(value).ToFullString();

    /// A report that parses as JSON but is not the array nuget-license writes.
    private sealed class InvalidReportException(string message) : System.Exception(message);

    /// Built inside one source output rather than carried through the pipeline, so reference
    /// equality is all it needs.
    private sealed class Package(string title, string? license, string? authors, string? projectUrl)
    {
        public string Title { get; } = title;

        public string? License { get; } = license;

        public string? Authors { get; } = authors;

        public string? ProjectUrl { get; } = projectUrl;
    }
}
